#!/usr/bin/env bash

# bib.sh:
#   A script for updating latex project '*.bib' library file.
#
#   This script, when bound to a global alias
#   makes it easy to copy-update the '*.bib'
#   library location from any child directory
#   of the project.
#
#
# author: Everett
# created: 2020-11-05 05:31
# Github: https://github.com/antiqueeverett/

# todo: find resource dir from any project child dir
# date: 2020-11-13 05:49

# source path of library.bib (auto-generated by mendeley)
dst='resources'
src="$HOME/Dropbox/academic/mendeley/library.bib"

temp="temp.bib"
bib="library.bib"


cleanup() {

# remove old temp file
if [ -f "$temp" ]; then
    rm -rf "$temp"
fi

# back up
cp  "$bib" "$temp"

# abbreviate ACM
sed -i -e 's/Association for Computing Machinery/ACM/g' "$bib"

# clear series
pattern="series ="
replace="series = {},"
sed -i "/$pattern/c$replace" "$bib"

# see changes
vimdiff "$temp" "$bib"
}

# bibupdate
#   Finds resource directory current
#   working latex project and copies
#   over the '*.bib' file.
bibupdate() {
    topmost=10
    FOUND=

    #   traverse parent directories upward to find resource directory
    for ((maxwalk = topmost; maxwalk > 0; --maxwalk)); do
        if [ -d "$dst" ]; then
            FOUND='yes'
            echo "Found latex project $dst directory"
            echo "Copy-updating $src => ./resources"
            cd ./resources || return
            cleanup
            cp "$src" ./
            return
        else
            cd "../"
        fi
    done
    if [ "$FOUND" = '' ]; then echo 'Resource directory not found' ;fi
}

bibupdate
